JueriShop/Controllers/HomeController.cs
using JueriShop.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;

namespace JueriShop.Controllers
{
    [Authorize(Roles="Administrator, User")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        [Authorize(Roles = "Administrator")]
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JueriShop/Controllers/JewelriesController.cs
#nullable disable
using JueriShop.Models;
using JueriShop.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace JueryShopPAW.Controllers
{
    public class JewelriesController : Controller
    {
        private readonly JewelryService _jewelryService;

        public JewelriesController(JewelryService jewelryService)
        {
            _jewelryService = jewelryService;
        }

        // GET: Jewelries
        public IActionResult Index()
        {
            var jewelries = _jewelryService.GetJewelries();
            return View(jewelries);
        }


        // GET: Jewelries/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jewelry = _jewelryService.GetJewelries().FirstOrDefault(m => m.IdJewel == id);
            if (jewelry == null)
            {
                return NotFound();
            }

            return View(jewelry);
        }

        // GET: Jewelries/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Jewelries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,IdCategory,Name,SerialNumber,Description,Price")] Jewelry jewelry)
        {
            if (ModelState.IsValid)
            {

                _jewelryService.AddJewelry(jewelry);
                _jewelryService.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(jewelry);
        }

        // GET: Jewelries/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jewelry = _jewelryService.GetJewelries().FirstOrDefault(m => m.IdJewel == id);
            if (jewelry == null)
            {
                return NotFound();
            }
            return View(jewelry);
        }

        // POST: Jewelries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,IdCategory,Name,SerialNumber,Description,Price")] Jewelry jewelry)
        {
            if (id != jewelry.IdJewel)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _jewelryService.UpdateJewelry(jewelry);
                    _jewelryService.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JewelryExists(jewelry.IdJewel))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(jewelry);
        }

        // GET: Jewelries/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jewelry = _jewelryService.GetJewelries().FirstOrDefault(m => m.IdJewel == id);
            if (jewelry == null)
            {
                return NotFound();
            }

            return View(jewelry);
        }

        // POST: Jewelries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var jewelry = _jewelryService.GetJewelryByCondition(b => b.IdJewel == id).FirstOrDefault();
            _jewelryService.DeleteJewelry(jewelry);
            _jewelryService.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool JewelryExists(int id)
        {
            return _jewelryService.GetJewelries().Any(e => e.IdJewel == id);
        }
    }
}



JueriShop/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About Page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sakura juerī</title>

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href="css/style.css">

</head>
<body>

<!-- header section starts  -->

<header>

    <input type="checkbox" name="" id="toggler">
    <label for="toggler" class="fas fa-bars"></label>

    <a href="#" class="logo">About us<span>.</span></a>

       <nav class="navbar">
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Jewelries" asp-action="Index">Products</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
    
    </nav>

    <div class="icons">
        <a href="#" class="fas fa-shopping-cart"></a>
        <a href="login.html" class="fas fa-user"></a>
    </div>

</header>

<!-- header section ends -->

<!-- home section starts  -->

<section class="home" id="home">

    <div class="content">
        <h3>Sakura Juerī</h3>
        <span>  </span>
        <p> </p>
        <a href="#" class="btn">shop now</a>
    </div>
    
</section>

<!-- home section ends -->
<section class="about" id="about">

    <h1 class="heading"> <span> about </span> us </h1>

    <div class="row">

        <div class="video-container">
            <video src="images/sakura.mp4" loop autoplay muted></video>
            <h3>best diamonds</h3>
        </div>

        <div class="content">
            <h3>why choose us?</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem cumque sit nemo pariatur corporis perspiciatis aspernatur a ullam repudiandae autem asperiores quibusdam omnis commodi alias repellat illum, unde optio temporibus.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusantium ea est commodi incidunt magni quia molestias perspiciatis, unde repudiandae quidem.</p>
            
        </div>

    </div>

</section>

<section class="footer">

    <div class="box-container">

        <div class="box">
            <h3>quick links</h3>
               
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Privacy</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">About</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Jewelries" asp-action="Index">Products</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Contact</a>
    
   
        </div>

        <div class="box">
            <h3>extra links</h3>
            <a href="#">my account</a>
            <a href="#">my order</a>
        </div>

        <div class="box">
            <h3>contact info</h3>
            <a href="#">+123-456-7890</a>
            <a href="#">example@gmail.com</a>
            <img src="images/payment.png" alt="">
        </div>
    </div>

    <div class="credit"> &copy;2022 Ciontu Claudia-Elena </div>

</section>

<!-- footer section ends -->

    
</body>
</html>

JueriShop/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h1>@ViewData["Title"]</h1>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sakura juerī</title>
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JueriShop.styles.css" asp-append-version="true" />
    <style>
.contact .row{
    display: flex;
    flex-wrap: wrap-reverse;
    gap:1.5rem;
    align-items: center;
}

.contact .row form{
    flex:1 1 40rem;
    padding:2rem 2.5rem;
    box-shadow: 0 .5rem 1.5rem rgba(0,0,0,.1);
    border:.1rem solid rgba(0,0,0,.1);
    background: #fff;
    border-radius: .5rem;
}

.contact .row .image{
    flex:1 1 40rem;
}

.contact .row .image img{
    width: 100%;
}

.contact .row form .box{
    padding:1rem;
    font-size: 1.7rem;
    color:#333;
    text-transform: none;
    border:.1rem solid rgba(0,0,0,.1);
    border-radius: .5rem;
    margin:.7rem 0;
    width: 100%;
}

.contact .row form .box:focus{
    border-color: var(--pink);
}

.contact .row form textarea{
    height: 15rem;
    resize: none;
}
</style>
</head>
<body>

<!-- header section starts  -->

<header>

    <input type="checkbox" name="" id="toggler">
    <label for="toggler" class="fas fa-bars"></label>

    <a href="#" class="logo">Contact<span>.</span></a>

      <nav class="navbar">
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Jewelries" asp-action="Index">Products</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
  
    </nav>

    <div class="icons">
        <a href="#" class="fas fa-shopping-cart"></a>
        <a href="login.html" class="fas fa-user"></a>
    </div>

</header>

<!-- header section ends -->

<!-- home section starts  -->

<section class="home" id="home">

    <div class="content">
        <h3>Sakura Juerī</h3>
        <span>  </span>
        <p> </p>
        <a href="#" class="btn">shop now</a>
    </div>
    
</section>

<!-- home section ends -->

<!-- contact section starts  -->

<section class="contact" id="contact">

    <h1 class="heading"> <span> contact </span> us </h1>

    <div class="row">

        <form action="">
            <input type="text" placeholder="name" class="box">
            <input type="email" placeholder="email" class="box">
            <textarea name="" class="box" placeholder="message" id="" cols="30" rows="10"></textarea>
            <input type="submit" value="send message" class="btn">
        </form>

        <div class="image">
            <img src="images/accesory-jewelry-svgrepo-com.svg" alt="">
        </div>

    </div>

</section>

<!-- contact section ends -->

<!-- footer section starts  -->

<section class="footer">

    <div class="box-container">

        <div class="box">
            <h3>quick links</h3>
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Privacy</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">About</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Jewelries" asp-action="Index">Products</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Contact</a>
    
        </div>

        <div class="box">
            <h3>extra links</h3>
            <a href="#">my account</a>
            <a href="#">my order</a>
        </div>

        <div class="box">
            <h3>contact info</h3>
            <a href="#">+123-456-7890</a>
            <a href="#">example@gmail.com</a>
            <img src="images/payment.png" alt="">
        </div>

    </div>

    <div class="credit"> &copy;2022 Ciontu Claudia-Elena </div>

</section>

<!-- footer section ends -->

    
</body>
</html>




JueriShop/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sakura juerī</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JueriShop.styles.css" asp-append-version="true" />
</head>
<body>

<!-- header section starts  -->

<header>

    <input type="checkbox" name="" id="toggler">
    <label for="toggler" class="fas fa-bars"></label>

    <a href="#" class="logo">Sakura Juerī<span>.</span></a>

    <nav class="navbar">
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Jewelries" asp-action="Index">Products</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
    
    </nav>

    <div class="icons">
        <a href="#" class="fa fa-shopping-cart"></a>
        <a href="login.html" class="fas fa-user"></a>
    </div>

</header>

<!-- header section ends -->

<!-- home section starts  -->

<section class="home" id="home">

    <div class="content">
        <h3>Sakura Juerī</h3>
        <span>  </span>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae laborum ut minus corrupti dolorum dolore assumenda iste voluptate dolorem pariatur.</p>
 <a class="btn" asp-area="" asp-controller="Jewelries" asp-action="Index">Products</a>
    </div>
    
</section>

<!-- home section ends -->

<!-- footer section starts  -->

<section class="footer">

    <div class="box-container">

        <div class="box">
            <h3>quick links</h3>
          <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Privacy</a>
  <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">About</a>
   <a class="nav-link text-dark" asp-area="" asp-controller="Jewelries" asp-action="Index">Products</a>
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Contact</a>
    
        </div>

        <div class="box">
            <h3>extra links</h3>
            <a href="#">my account</a>
            <a href="#">my order</a>
        </div>

        <div class="box">
            <h3>contact info</h3>
            <a href="#">+123-456-7890</a>
            <a href="#">example@gmail.com</a>
            <img src="images/payment.png" alt="">
        </div>

    </div>

    <div class="credit"> &copy;2022 Ciontu Claudia-Elena </div>

</section>

<!-- footer section ends -->

    
</body>
</html>